root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2017
  project: tsconfig.json
  sourceType: module

plugins:
  - "@typescript-eslint"

extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier

env:
  node: true
  jest: true
  es6: true

rules:
  '@typescript-eslint/interface-name-prefix': "off"
  '@typescript-eslint/explicit-function-return-type': "off"
  '@typescript-eslint/explicit-module-boundary-types': "off"
  '@typescript-eslint/no-unsafe-call': "off"
  '@typescript-eslint/no-unsafe-return': "off"
